# test_xiaobai_2.py
# coding: utf-8
'''


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Fib:
f(n)=f(n-1) + f(n-2) < 4000000

key point:
while True:
	break
'''

def findFib(number):
	if number == 1:
		return 1
	elif number == 2:
		return 2
	else:
		return findFib(number-1) + findFib(number-2)

if __name__ == '__main__':
	i = 1
	while True:
		value = findFib(i)
		if value > 4000000:
			print i
			break
		i+=1
	



